### ISSUE TITLE
I can't use the site to watch movies with my friends.

### ISSUE THREAD

**Issue by limmynade** [tymmesyde/peario-client#1]
A few days ago my friend told me about the site and we used it a few times, had no problems with the site until yesterday when the site didn't work for both of us. The site shows nothing and i cant do anything but change the language.
![image](https://user-images.githubusercontent.com/63409479/87201079-8cf04c80-c306-11ea-9977-d6709ee20c58.png)

**Comment by tymmesyde** [comment]
Sorry for that, there was an issue with the server.
It should be fixed now !

**Comment by limmynade** [comment]
thanks a lot!!
