### ISSUE TITLE
Getting "Stremio is not running" error

### ISSUE THREAD

**Issue by igoracmelo** [tymmesyde/peario-client#10]
**Describe the bug**
When I access peario.xyz I get this error message:
![image](https://user-images.githubusercontent.com/85039990/148791386-08a13690-ec38-497b-acb6-1b23535861d0.png)

I inspect the console and in fact the request is beeing blocked:
![image](https://user-images.githubusercontent.com/85039990/148792085-2e2b4d08-a6e3-4360-97c9-26b909e89a91.png)

I found out that it was because of the adblock (specifically, Brave browser's adblock):
![image](https://user-images.githubusercontent.com/85039990/148791958-0a265b2d-291f-4b13-98e2-d60f766d3f7b.png)

So I thought maybe it would be a good idea to **warn user that the adblock is blocking the request or something like that**, because the user may not be able to find that out.

**Comment by tymmesyde** [comment]
Hi, thank you for your remark
This is indeed a good idea and will add it !

**Comment by igoracmelo** [comment]
I took a look at the code.
It doesn't seem to be hard to solve.
I will try to code that today, ok?
