### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GerdBurger** [tymmesyde/peario-client#14]
How would i know if torrentio is using real debrid?

**Comment by tymmesyde** [comment]
You will see [RD+] on the title of the stream, same thing for other debrid services

![image](https://user-images.githubusercontent.com/7889816/167331124-91a4eee4-2a52-4837-872d-cf0b50686dc2.png)

**Comment by GerdBurger** [comment]
how would i add my torrentio with real debrid? it just says "Torrentio 4k".

**Comment by tymmesyde** [comment]
@GerdBurger
Open Stremio, go to your addon click the share link icon on for the addon that you want to add,
Go to Peario, open the Addons tabs and paste the link in the input and press enter
You'll see your newly added addon and can activate it.

![image](https://user-images.githubusercontent.com/7889816/168412157-a2f2233e-81f3-49ac-886c-3b2375c37b26.png)
![image](https://user-images.githubusercontent.com/7889816/168412167-58619561-a01e-4533-b282-bb41f7cff600.png)
