### ISSUE TITLE
No Audio playing | Audio play but no video

### ISSUE THREAD

**Issue by TheQuadOne** [tymmesyde/peario-client#15]
I have been trying to use Peario addon. But I keep facing 2 problems. 1 -  there's no audio just video, 2 - There's audio but not video. I have tested that on Opea GX, Fire fox, google chrome. and tried 2 different addons (Torrentio and Piratebay) as well as different shows and movies. The first problem (no audio) is more common than the second

**Comment by sluzy-nos4a2** [comment]
Yes, I'm having the same issue on my brothers computer

**Comment by PAULeD16** [comment]
I am also having Video but no audio when watching on chrome and phone link

**Comment by tymmesyde** [comment]
Some browsers do not have the necessary codecs to play the audio from some streams, try switching to another browser like Edge or click the magic wand icon on the player.
