### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zykrah** [tymmesyde/peario-client#2]
Hey there, I'm really glad to see you're still maintaining this project :)

I used to use this with my friends and I'm glad to see that it's still being improved.

Although I'm curious, is it possible to set a username or change from "GuestXXXXX"?

And a suggestion if you are looking for ideas, could you add some sort of feature to hand over "admin" powers to someone else in case the original owner has to leave?

Lastly, I believe subtitles are broken (limited testing).

Once again, thanks for the plugin!

**Comment by tymmesyde** [comment]
Hi ~
Updating the username is in my feature list :)
Yeah that could be nice, i'll see what i can do but cannot promise you anything..
I believe this is due to some changes made on the stremio server, i'll try fixing this !

**Comment by tymmesyde** [comment]
Closing: was implemented or fixed
