### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by ylmzcbk** [tymmesyde/peario-client#21]
**Describe the bug**
When I try to add a new add-on, I get CORS error instead.

**To Reproduce**
1. Copy add-on's manifest link.
2. Paste it to Peario's add-on manager.
3. Open browser's console to see the error.

**Expected behavior**
I was expecting that the add-on to be added.

**Screenshots**
![Screenshot 2022-04-17 193328](https://user-images.githubusercontent.com/10196055/163723840-634cceb7-7243-4a83-8b36-5ce1cfd9be2a.png)

**Environment**
 - Windows 11 x64
 - Edge, Chrome, Firefox Developer, Opera

**Comment by tymmesyde** [comment]
You need to paste the direct url to the manifest addon, i believe you pasted the url to share the manifest from Stremio
Try pasting this instead: https://torrentio.strem.fun/manifest.json
