### ISSUE TITLE
Subtitles not working 

### ISSUE THREAD

**Issue by FeridunDuran** [tymmesyde/peario-client#3]
When I use the subtitle option on the  right corner loading sing constantly spinning and doesnt load any subtitles. This happens in any movie or series.
 Im using latest stremio 4.4.142 and latest chrome beta version 94.0.4606.31 (Official Build) beta (64-bit)

**Comment by tymmesyde** [comment]
Thanks for submitting your issue !
The only thing I can do about that is to implement subtitles addons which will be available very soon, either today or tomorrow.

**Comment by tymmesyde** [comment]
Closing this issue, you should now be able to add Subtitles Addons which will provide you with more.

**Comment by sluzy-nos4a2** [comment]
I have the same issue when watching series, I've added the opensubtitles add-on with the URL [https://subtitlesv2.strem.io/manifest.json](https://subtitlesv2.strem.io/manifest.json) but when watching series no subtitle appear.

**Comment by tymmesyde** [comment]
> I have the same issue when watching series, I've added the opensubtitles add-on with the URL https://subtitlesv2.strem.io/manifest.json but when watching series no subtitle appear.

This addon does work for me
Did you make sure that the addon appear in the addon list after entering the manifest url ? And that it's activated ?

![image](https://user-images.githubusercontent.com/7889816/164987236-2f1a9806-e872-4040-a7ee-f7e90cf3b1e9.png)

**Comment by sluzy-nos4a2** [comment]
> 
Yes, that is not the problem, the opensubtitles add-on is in the list and is activated.

![image](https://user-images.githubusercontent.com/66081804/164993078-074e8a65-68d1-4a79-aba2-e487829ea237.png)

And when watching a movie, the subtitles do actually work

![image](https://user-images.githubusercontent.com/66081804/164993133-6f0f7520-eeb7-49e7-9f48-d0c8585ae8e8.png)

But when watching an episode from some serie it doesn't seem to work
![image](https://user-images.githubusercontent.com/66081804/164993214-8499f542-dfc5-46ed-ba8c-2bae04152c99.png)

There are also some plugins that I can't add like [https://subtitles-stremio-addon.herokuapp.com/manifest.json](https://subtitles-stremio-addon.herokuapp.com/manifest.json) and [https://subtitles-stremio-addon.herokuapp.com/manifest.json](https://subtitles-stremio-addon.herokuapp.com/manifest.json), when I try to add them nothing happens.

![image](https://user-images.githubusercontent.com/66081804/164993276-05571f6b-dbce-48e6-b735-54c0b7cfd201.png)
