### ISSUE TITLE
Some streams doesnt play any video just plays audio

### ISSUE THREAD

**Issue by FeridunDuran** [tymmesyde/peario-client#4]
Some of the streams doesnt play any video for example suicide squad 2021's most seeded torrentio stream(The Suicide Squad 2021 2160p WEBRip👤 1344 💾 5.9 GB ⚙️ YTS) just shows movies poster and plays audio. 
Sometimes switching to HLS stream works but in HLS quality signicantly decreases and often times it doesnt even play

**Comment by tymmesyde** [comment]
When this happen, try another stream or try switching browser for firefox or edge for example.
Unfortunately HLS will not work from now on due to the stremio-server now restricting some endpoints to only their domains.

**Comment by the-nos4a2** [comment]
https://user-images.githubusercontent.com/66081804/209544836-766e3a97-9022-4ba8-ae4c-e6ab46e08ca0.mp4

**Comment by the-nos4a2** [comment]
https://user-images.githubusercontent.com/66081804/209544934-217427aa-4355-4ce9-9d59-f81837bb0e33.mp4
