### ISSUE TITLE
Audio Bug

### ISSUE THREAD

**Issue by daviplutao** [tymmesyde/peario-client#40]
I can't say with 100% accuracy, but I think there's a certain bug with some extensions, that in some series and movies the audio just doesn't appear, there's no audio.  I use Brazilian extensions because I'm Brazilian 🇧🇷!
.
.
.
It would be nice if you could fix this, please.

**Comment by tymmesyde** [comment]
Some browser don't have the necessary codecs to play the audio from some streams, try to use another browser like edge or click the magic wand button on the player
