### ISSUE TITLE
Can't scroll on firefox

### ISSUE THREAD

**Issue by ang3lo-azevedo** [tymmesyde/peario-client#42]
**Describe the Bug**
On every scrollable area on the website, like the films list or the streams I'm unable to scroll.

**Comment by tymmesyde** [comment]
Can you provide an example or a video ?
I'm also using firefox and can't reproduce this

**Comment by the-nos4a2** [comment]
https://user-images.githubusercontent.com/66081804/209544994-39cb1836-ea3a-44db-86d0-93de70226491.mp4

**Comment by tymmesyde** [comment]
Fixed
