### ISSUE TITLE
non of the addons work

### ISSUE THREAD

**Issue by hyut4** [tymmesyde/peario-client#44]
no streams are showing and non of the add-ons is working I tried everything I reinstalled the app and also updated my pc still nothing is working

**Comment by tymmesyde** [comment]
Use this website to get a community list of addons: https://stremio-addons.netlify.app/
Then click the Copy Link and paste it on Peario here: 
![image](https://user-images.githubusercontent.com/7889816/225486092-6f12ada3-ce5e-4108-8eb7-09ce03f060f1.png)
![image](https://user-images.githubusercontent.com/7889816/225486225-a5d8819a-4f44-40fd-9f35-f382d86ecefa.png)

**Comment by tymmesyde** [comment]
Updated the ux of the addons panel
