### ISSUE TITLE
No streams available

### ISSUE THREAD

**Issue by banditelvis721** [tymmesyde/peario-client#45]
I keep getting no streams available i chose the addons

i use stremio and when i pick a movie and use peario addon to watch with a friend it goes to peario website and says no streams available why is that???

![image](https://user-images.githubusercontent.com/39413154/225324005-632f2374-a91e-4a4f-956c-8599cba500b9.png)

**Comment by tymmesyde** [comment]
Did you installed addons by clicking Manage Addons ?

**Comment by banditelvis721** [comment]
I got it thank you
