### ISSUE TITLE
Stremio web support

### ISSUE THREAD

**Issue by load1n9** [tymmesyde/peario-client#46]
would be cool to be able to use the stremio web thing to pretty much spin up an instance in peario itself

**Comment by tymmesyde** [comment]
Hi ! Can you elaborate a bit more on your suggestion ?

**Comment by load1n9** [comment]
so the idea would be that the user would not need to have stremio open and we can get a stremio instance loaded in the browser headlessly

**Comment by tymmesyde** [comment]
> so the idea would be that the user would not need to have stremio open and we can get a stremio instance loaded in the browser headlessly

The reason why it needs stremio running to work is because Stremio desktop is running a stremio server instance, which is the streaming engine, without it it cannot stream torrents.
You don't need the stremio server running when watching a http stream

**Comment by load1n9** [comment]
Ik but the idea is to maybe then have a stremio server instance running from the peario server

**Comment by tymmesyde** [comment]
> Ik but the idea is to maybe then have a stremio server instance running from the peario server

It is not possible to run a stremio server instance from the peario server
`peario-server` is just a websocket server that run on a vps, it allows users to create rooms and sync with each others
`stremio-server` is a torrent streaming engine that runs locally on the user's machine
`stremio-web` is a website/interface that connects to `stremio-server` to stream torrents just like `peario-client`
