### ISSUE TITLE
Adblock is on streamio how do I disable it

### ISSUE THREAD

**Issue by Allen1283** [tymmesyde/peario-client#50]
**Describe the bug** on streamio adblock is turned on how do I turn it off

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
 - Platform [e.g. desktop, mobile]

**Additional context**

**Comment by tymmesyde** [comment]
@Allen1283 This is not a page to post questions related to Stremio nor AdBlock, this is about Peario
To disable adblock on a website you just click on the extension and click the toggle, if you don't manage do to it, you can also find tutorials on how to do it on the internet
