### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by batuhancelasun** [tymmesyde/peario-client#51]
**Describe the bug**
There is no sound.

**To Reproduce**
Every content.

**Expected behavior**
I want to watch it with sound.

**Environment**
 - Desktop / torrentio
 - Chrome

**Comment by tymmesyde** [comment]
Hey, can you be a bit more specific, like what addon did you use, what kind of stream did you play ?

**Comment by batuhancelasun** [comment]
I used torrentio addon and i watched TV series.

**Comment by tymmesyde** [comment]
I can only recommend you to try this:
> switch to a different browser, try other streams or click the magic wand on the player

**Comment by batuhancelasun** [comment]
Thank you
