### ISSUE TITLE
Idioma 

### ISSUE THREAD

**Issue by x109ma** [tymmesyde/peario-client#53]
No sé puede pasar a un idioma español solo inglés

**Comment by tymmesyde** [comment]
Si te refieres a los subtítulos, puedes encontrar más aquí o hacer clic en el botón para abrir la lista de addons de la comunidad
![image](https://github.com/tymmesyde/peario-client/assets/7889816/23f68210-095a-4f19-a5f2-262e582f1dac)
![image](https://github.com/tymmesyde/peario-client/assets/7889816/a5787db0-3490-4a2f-b864-7e1dc9514398)
