### ISSUE TITLE
Can you use Peario with Debrid links 

### ISSUE THREAD

**Issue by Viren070** [tymmesyde/peario-client#67]
Apologies for creating an issue. 
However, I wanted to ask if using Peario to stream Debrid links counts (to the Debrid service) as streaming from multiple IP addresses.

**Comment by tymmesyde** [comment]
Hi, no problem
Yes because the other people in the room will use your debrid link, this means to the provider that you are connecting from multiple ip addresses
I believe that Premiumize doesn't care about this, it might be the case for other providers

**Comment by Viren070** [comment]
Alright, thanks for the response. I appreciate the time that you put into developing this addon and wish you the best.
