### ISSUE TITLE
Cannnot connect to the server 

### ISSUE THREAD

**Issue by Saitashun** [tymmesyde/peario-client#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**
![Screenshot_20211116-224839](https://user-images.githubusercontent.com/88075832/142033799-c2bb0bae-2024-4f44-ba34-e3e84668c654.jpg)

**Screenshots**

**Environment**
 - Platform [e.g. desktop, mobile]

**Additional context**

**Comment by tymmesyde** [comment]
Is this still happening to you ?
