### ISSUE TITLE
Can’t connect peario to Stremio 

### ISSUE THREAD

**Issue by Cklinewv2** [tymmesyde/peario-client#71]
**Describe the bug**
Says you don’t an app for this when you click on it

**To Reproduce**

**Expected behavior**

**Screenshots**
[![IMG_0651](https://github.com/tymmesyde/peario-client/assets/174748455/739d168a-dd5e-44f1-b62d-657d17ac4a34)
](url)

**Environment**
 - Platform [e.g. desktop, mobile]

**Additional context**

**Comment by tymmesyde** [comment]
This is an issue with the Stremio Android TV app, it says that you don't have a browser that can open this url: `https://peario.xyz`
