### ISSUE TITLE
Streams are not running

### ISSUE THREAD

**Issue by Butterflyfflower** [tymmesyde/peario-client#9]

**Comment by Butterflyfflower** [comment]
So what should I do ?

**Comment by tymmesyde** [comment]
Why do you mean by streams are not running ?
Do you have Stremio open ?

**Comment by Butterflyfflower** [comment]
When I try to open a movie or serial that's the message that gives in the screen and doesn't open  nothing just loading loading and stays like that for 10 m or more

**Comment by tymmesyde** [comment]
Can you send me a screenshot ?

**Comment by Butterflyfflower** [comment]
I already unsubscribe

**Comment by tymmesyde** [comment]
> I already unsubscribe

To what ?

**Comment by Butterflyfflower** [comment]
Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by tymmesyde** [comment]
Can you send me a screenshot of the issue you're experiencing ?

**Comment by Butterflyfflower** [comment]
There it is

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by tymmesyde** [comment]
It's really not, you're forwarding the GitHub email notifications you received

**Comment by Butterflyfflower** [comment]
No, I'm   answering to the questions that you are being doing ...I'm not understanding nothing already just let go ..

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
